import Head from "next/head";
import About from "../components/About";
import Project from "../components/Projects";
import Contact from "../components/Contact";
import Landing from "../components/Landing";
import Navbar from "@/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-sans bg-black text-white">
        <Navbar />
        <Landing />
        <About />
        <Project />
        <Contact />
      </main>
    </>
  );
}
